### PR TITLE
Jet sett/better relationship

### PR DESCRIPTION
**Pull request by jetSett**
/ressources/<uid>?includes=field1,field2,field3  load related resources to the resource <uid> in the relationship fields field1, field2...

### CODE REVIEW

**Comment by flupe** [comment]
That's cool!
Before merging, can you name the parameter `include` just as in the JSONAPI spec?
Does it work for nested inclusions? (I don't think it does right now, but would be rather useful)
Does if work for relationships? (See #25)

**Comment by liautaud** [comment]
@flupe Once this is merged, do you plan on updating the JS API (and especially making it work with the `resouceMixin`)? Or would you rather have someone else do it?

**Comment by flupe** [comment]
Well I am working on the taxonomy right now, so if you want to do it suit yourself!
But I don't think this will be merged right away, so maybe we should wait a bit before touching the JS part.

**Comment by Lapin0t** [comment]
So yeah just formalizing what @flupe said and adding a few of my own:

* the query name should be renamed to `?include=...` to stick a bit more to JSON API
* it would be great if the relationship endpoints `GET resources/{id}/{rel}` would support `?include` (without argument)
* the format of the `included` field of the response should be a dict `{UUID => resource object}` (not `{field-name => {UUID => resource object}`)

On code organisation: maybe a good idea would be to move that code to the `Store.read` function with an optional argument `include`. The return type of `read` could be changed to be the full answer: `{"data": <main-resource>, "includes": <additional resources if any>}`. This could enable easy implementation of nested inclusions (ie `?include=foo.bar` is implemented by loading the main resource and including target of `foo` relationship with `include=["bar"]` and then merging the 2 responses). Note that this is only a suggestion.

**Comment by flupe** [comment]
> the format of the included field of the response should be a dict `{UUID => resource object}`
> (not `{field-name => {UUID => resource object}}`)

Actually, in the JSON API Spec, compound documents (documents that return more than one resource via the `include` parameter), should have the `included` field in the response be a **flat array of resource objects**. This would be simpler for me to handle in the JS (well, at least prettier), so I think it would be better to have that rather than a dict. (See http://jsonapi.org/format/#document-compound-documents)

**Comment by Lapin0t** [comment]
> flat array

Don't you think that your primary operation will be to get these resource objects by UUID?

**Comment by flupe** [comment]
Well no, since my goal was that the resources in this flat array be automatically added to the local store..
So you still go by `tozti.store.get`.

**Comment by Lapin0t** [comment]
Ok, i guess that's fine then (and it's even on par with JSON API).

**Comment by liautaud** [comment]
Holy shit, what just happened?

**Comment by liautaud** [comment]
Il y a du sacré déterrage dans l'air 😂

**Comment by jetSett** [comment]
Ouais, elle trainait dans mes PR pas fermées, ça me soulais x)

**Comment by Lapin0t** [comment]
Bonjour

**Comment by liautaud** [comment]
Salu sava?

**Comment by gldubc** [comment]
🙋‍♂️

**Pull request closed without merging**
